# Generated by Django 4.2 on 2024-09-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['id'], 'verbose_name': 'Friend Request', 'verbose_name_plural': 'Friend Requests'},
        ),
    ]
