# Generated by Django 4.2 on 2024-09-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_alter_friendrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['id'], 'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
    ]
