# Generated by Django 4.2 on 2024-09-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_account_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
